{% set name = "pywaterflood" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pywaterflood-{{ version }}.tar.gz
  sha256: ba608bef9d5e7506e5d7aa0800bf4de5da26e7e3c3f6e165e4ce9f9ed9fcc869

build:
  noarch: python
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - rust
    - cargo-bundle-licenses
  host:
    - python >=3.7
    - maturin >=0.13
    - pip
    - rust
  run:
    - python >=3.7
    - numpy >=1.21
    - scipy >=1.4
    - pandas >=1.3.5
    - openpyxl >=3.0.9
    - joblib >=1.1.0

test:
  imports:
    - pywaterflood
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Physics-inspired waterflood performance modeling
  home: https://pywaterflood.readthedocs.io
  license: BSD-2-Clause
  license_file:
    - THIRDPARTY.yml
    - LICENSE

extra:
  recipe-maintainers:
    - frank1010111
